package templates

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/binkovsky/forktrust/internal/config"
)

// TestAllTemplatesAreValid is the registry health check: every shipped
// template must parse as TOML AND pass RepoConfig.Validate(). If you add a
// new template, this test catches the common mistakes (bad regex in
// require_ticket_pattern, empty commands, malformed vars name).
func TestAllTemplatesAreValid(t *testing.T) {
	for _, tmpl := range All() {
		t.Run(tmpl.Name, func(t *testing.T) {
			dir := t.TempDir()
			path := filepath.Join(dir, ".forktrustconfig")
			if err := os.WriteFile(path, []byte(tmpl.Content), 0o644); err != nil {
				t.Fatal(err)
			}
			cfg, err := config.LoadRepoConfig(dir)
			if err != nil {
				t.Fatalf("template %q failed config load+validate: %v", tmpl.Name, err)
			}
			if cfg == nil {
				t.Fatalf("template %q produced nil config (empty file?)", tmpl.Name)
			}
		})
	}
}

// TestAllTemplatesHaveHeader: every template must start with a "Generated by"
// header so users grepping a .forktrustconfig in a strange repo immediately
// know it came from `forktrust init` and which template was picked.
func TestAllTemplatesHaveHeader(t *testing.T) {
	for _, tmpl := range All() {
		first := strings.SplitN(tmpl.Content, "\n", 2)[0]
		if !strings.HasPrefix(first, "# Generated by:") {
			t.Errorf("template %q first line lacks `# Generated by:` provenance header: %q", tmpl.Name, first)
		}
	}
}

// TestGet returns the named template or (zero, false).
func TestGet(t *testing.T) {
	x, ok := Get("nextjs")
	if !ok {
		t.Fatal("nextjs should be in the registry")
	}
	if x.Name != "nextjs" {
		t.Errorf("Get returned name=%q, want nextjs", x.Name)
	}
	_, ok = Get("does-not-exist-xyz")
	if ok {
		t.Error("Get for missing name should return ok=false")
	}
}

// TestAllSorted: All() returns deterministic order so `template list` output
// and any fixtures based on it remain stable.
func TestAllSorted(t *testing.T) {
	all := All()
	for i := 1; i < len(all); i++ {
		if all[i-1].Name > all[i].Name {
			t.Errorf("All() not sorted: %q > %q at index %d", all[i-1].Name, all[i].Name, i)
		}
	}
}

// TestDetectPathsExist: every Detect path should look like a real
// well-known file (smoke-check that no typo crept in, e.g. "pacakge.json").
// This is a soft check — we just refuse blatantly empty entries.
func TestDetectPathsNonEmpty(t *testing.T) {
	for _, tmpl := range All() {
		for i, p := range tmpl.Detect {
			if strings.TrimSpace(p) == "" {
				t.Errorf("template %q Detect[%d] is empty/whitespace", tmpl.Name, i)
			}
		}
	}
}
