// Package templates ships canonical .forktrustconfig starters for common
// project types so `forktrust init` can scaffold a sensible config without
// the user having to read the full reference docs first. Each template is
// embedded as a Go string constant; the registry exposes them by name.
//
// All templates MUST be valid TOML AND must pass config.LoadRepoConfig's
// Validate() — there is a unit test that enforces this for the whole
// registry, so adding a broken template breaks CI.
//
// v0.7.9 introduced.
package templates

import (
	"sort"
)

// Template is one named starter for .forktrustconfig.
type Template struct {
	Name        string // CLI-facing name, e.g. "nextjs"
	Description string // one-line, shown by `forktrust template list`
	// Detect is a list of relative paths whose presence in cwd suggests
	// this template fits. Empty means "no auto-detect" (e.g. minimal).
	// Multiple paths AND together (all must exist); for OR semantics add
	// the template more than once or post-filter in init.
	Detect []string
	// Content is the literal .forktrustconfig bytes written on init.
	Content string
}

// All returns the registry sorted by Name. Stable order so `template list`
// output is deterministic and tests can diff against fixtures.
func All() []Template {
	out := make([]Template, 0, len(registry))
	for _, t := range registry {
		out = append(out, t)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

// Get returns the named template (ok=false if missing). Names are matched
// case-sensitively — keep them all lowercase + kebab so users do not have
// to guess.
func Get(name string) (Template, bool) {
	t, ok := registry[name]
	return t, ok
}

// registry is keyed by Template.Name. Adding an entry here automatically
// makes it discoverable via List/Get/CLI without further wiring.
var registry = map[string]Template{
	"minimal": {
		Name:        "minimal",
		Description: "bare-minimum: copy .env.local into worktrees, nothing else",
		Detect:      nil, // explicit pick only
		Content:     minimalTemplate,
	},
	"nextjs": {
		Name:        "nextjs",
		Description: "Next.js: copy .env files, allocate per-worktree port block, verify with `npm run build`",
		Detect:      []string{"package.json"}, // init.go further inspects for "next" dep
		Content:     nextjsTemplate,
	},
	"nextjs-strict": {
		Name:        "nextjs-strict",
		Description: "Next.js + [summary] Conventional Commits contract (closes the merge gate trilogy)",
		Detect:      nil, // explicit pick only — opinionated overlay
		Content:     nextjsStrictTemplate,
	},
	"go-cli": {
		Name:        "go-cli",
		Description: "Go CLI: verify with `go build / go test / go vet`",
		Detect:      []string{"go.mod"},
		Content:     goCliTemplate,
	},
	"python-poetry": {
		Name:        "python-poetry",
		Description: "Python + poetry: verify with `poetry check && poetry run pytest`",
		Detect:      []string{"pyproject.toml"}, // init.go further inspects for "[tool.poetry]"
		Content:     pythonPoetryTemplate,
	},
	"strict-ai": {
		Name:        "strict-ai",
		Description: "policy pack: AI-agent-focused [verify]+[summary] defaults; project-agnostic, layer on your own [ports]/[[hooks]]",
		Detect:      nil,
		Content:     strictAITemplate,
	},
}

// --- template bodies. All start with a `# Generated by forktrust template ...`
// header so users (and reviewers) can identify the source without grepping. ---

const minimalTemplate = `# Generated by: forktrust init --template minimal
# Reference: https://github.com/binkovsky/forktrust/blob/main/docs/config.md

# Copy .env.local from the main checkout into every new worktree, so dev
# servers in the worktree pick up the same secrets. Adjust the source path
# if your env files live elsewhere.
[[hooks.post_create]]
type = "copy"
from = ".env.local"
to   = ".env.local"
`

const nextjsTemplate = `# Generated by: forktrust init --template nextjs
# Reference: https://github.com/binkovsky/forktrust/blob/main/docs/config.md

# Per-worktree port block so parallel ` + "`next dev`" + ` servers do not collide.
# Each worktree gets PORT=3000+10*N through PORT_END=PORT+9.
[ports]
range = "3000-3099"
size  = 10
vars  = ["PORT"]

# Copy env files into the worktree so the dev server has its secrets.
[[hooks.post_create]]
type = "copy"
from = ".env.local"
to   = ".env.local"

[[hooks.post_create]]
type = "copy"
from = ".env.development.local"
to   = ".env.development.local"

# Refuse to merge unless the build passes. Catches type errors, missing deps,
# bad imports. Add lint/test commands here if you have them.
[verify]
commands        = ["npm run build"]
timeout_seconds = 600  # next build can be slow on cold cache
`

const nextjsStrictTemplate = `# Generated by: forktrust init --template nextjs-strict
# Reference: https://github.com/binkovsky/forktrust/blob/main/docs/config.md
#
# This is the "merge gate trilogy" config for Next.js: ports + hooks +
# verify (tests/build pass) + summary (commit messages explain WHY).
# Pair with ` + "`forktrust new <slug> --scope \"src/**, app/**\"`" + ` for the third side.

[ports]
range = "3000-3099"
size  = 10
vars  = ["PORT"]

[[hooks.post_create]]
type = "copy"
from = ".env.local"
to   = ".env.local"

[verify]
commands        = ["npm run build", "npm test --silent --if-present"]
timeout_seconds = 600

# Conventional Commits-ish contract. Every commit must:
#   - start with one of these prefixes (Conventional Commits)
#   - have a body of at least 20 bytes explaining the why
#   - not contain "WIP" or "TODO" anywhere
# Bypass: ` + "`forktrust finish --no-summary`" + ` (logs a warning).
[summary]
required               = true
min_body_length        = 20
require_subject_prefix = ["feat", "fix", "refactor", "docs", "chore", "test", "perf", "build", "ci", "style", "revert"]
forbidden_patterns     = ["WIP", "TODO", "TBD", "fixup!"]
`

const goCliTemplate = `# Generated by: forktrust init --template go-cli
# Reference: https://github.com/binkovsky/forktrust/blob/main/docs/config.md

# Optional: copy .env if your binary reads it at runtime.
[[hooks.post_create]]
type = "copy"
from = ".env"
to   = ".env"

# Standard Go merge gate: build, test, vet must all pass. Add ` + "`golangci-lint run`" + `
# if you use it. ` + "`-race`" + ` flushes most data races but doubles test time —
# include it on CI but maybe drop it from the local gate for speed.
[verify]
commands        = ["go build ./...", "go test ./... -race -timeout 120s", "go vet ./..."]
timeout_seconds = 600
require_clean   = true  # refuse if tests/build wrote uncommitted byproducts
`

const pythonPoetryTemplate = `# Generated by: forktrust init --template python-poetry
# Reference: https://github.com/binkovsky/forktrust/blob/main/docs/config.md

# Copy env file into worktree.
[[hooks.post_create]]
type = "copy"
from = ".env"
to   = ".env"

# Poetry-aware verify gate. ` + "`poetry check`" + ` validates pyproject.toml against
# the lockfile; ` + "`poetry run pytest`" + ` runs your test suite inside the project venv.
[verify]
commands        = ["poetry check", "poetry run pytest -q"]
timeout_seconds = 900
`

const strictAITemplate = `# Generated by: forktrust init --template strict-ai
# Reference: https://github.com/binkovsky/forktrust/blob/main/docs/config.md
#
# AI-agent-focused policy pack. Does NOT include project-specific bits
# (ports, hooks, build commands) — layer those in based on your stack.
# This file is meant to be the merge-gate scaffold; combine with:
#   * ` + "`forktrust new <slug> --scope \"globs\"`" + ` per task (change contract)
#   * ` + "`[verify]`" + ` commands from a project-type template (nextjs, go-cli, ...)

# Commit-message contract. Tight enough to keep agents honest, loose enough
# that humans don't fight it. Tighten by adding require_ticket_pattern.
[summary]
required               = true
min_body_length        = 30
require_subject_prefix = ["feat", "fix", "refactor", "docs", "chore", "test", "perf", "build", "ci", "style", "revert"]
forbidden_patterns     = ["WIP", "TODO", "FIXME", "TBD", "lorem", "fixup!", "DO NOT MERGE"]
`
